export const guides = {
  "ebed-otletek": {
    eyebrow: "Ebédtervezés",
    title: "Mit főzzek ebédre? Házias ebédötletek hétköznapokra és hétvégére",
    intro: "Az ebéd akkor működik jól, ha illik a rendelkezésre álló időhöz, az otthoni alapanyagokhoz és ahhoz is, mennyire szeretnél tartalmas ételt. Az alábbi ötletekből gyorsan összeállíthatsz egyszerű vagy háromfogásos menüt.",
    ideas: ["Csirkepaprikás nokedlivel", "Rakott krumpli", "Túrós csusza", "Gombapaprikás galuskával", "Paradicsomos húsgombóc", "Tökfőzelék fasírttal", "Lecsó kolbásszal", "Bácskai rizses hús", "Rántott hús körettel", "Zöldséges rizottó", "Húsleves", "Almás pite"],
    randomizerIdeas: ['Csirkepaprikás nokedlivel', 'Rakott krumpli', 'Túrós csusza', 'Gombapaprikás galuskával', 'Paradicsomos húsgombóc', 'Tökfőzelék fasírttal', 'Lecsó kolbásszal', 'Bácskai rizses hús', 'Rántott hús petrezselymes krumplival', 'Zöldséges rizottó', 'Húsleves cérnametélttel', 'Almás pite', 'Marhapörkölt galuskával', 'Székelykáposzta', 'Töltött káposzta', 'Brassói aprópecsenye', 'Paprikás krumpli kolbásszal', 'Sertéspörkölt tarhonyával', 'Bakonyi sertésszelet', 'Mátrai borzaska', 'Rántott csirkemell rizzsel', 'Sült csirkecomb burgonyával', 'Fokhagymás sertésszelet', 'Stefánia vagdalt', 'Fasírt krumplipürével', 'Zöldborsófőzelék fasírttal', 'Lencsefőzelék sült virslivel', 'Babfőzelék tükörtojással', 'Sárgaborsó-főzelék', 'Kelkáposzta-főzelék', 'Finomfőzelék', 'Rakott karfiol', 'Rakott kel', 'Rakott cukkini', 'Töltött paprika', 'Töltött cukkini', 'Krumplis tészta', 'Káposztás tészta', 'Mákos tészta', 'Diós tészta', 'Milánói sertésborda', 'Bolognai spagetti', 'Tejszínes-gombás csirke', 'Mustáros csirke rizzsel', 'Csirkés rizottó', 'Zöldséges csirkemell kuszkusszal', 'Hortobágyi húsos palacsinta', 'Túrógombóc', 'Aranygaluska vaníliasodóval', 'Palacsinta lekvárral'],
    sections: [
      { title: "Hétköznapi ebéd kevés időből", paragraphs: ["Munka mellett érdemes olyan fogást választani, amely kevés előkészítést kér, egy edényben elkészül, vagy másnap is jól újramelegíthető. A paprikás krumpli, a rizses hús, a főzelékek és a rakott ételek ezért praktikusak.", "Ha előző este előkészíted a zöldségeket vagy a köretet, másnap jelentősen rövidülhet a tényleges főzési idő."], bullets: ["Egytálételhez elég lehet egy friss saláta.", "Főzelékhez tojás, fasírt vagy sült hús adhat fehérjét.", "Rakott ételből érdemes két napra főzni.", "Leves mellé könnyebb főételt válassz."] },
      { title: "Hétvégi, ráérősebb menü", paragraphs: ["Hétvégén jöhetnek a hosszabban készülő klasszikusok, például húsleves, pörkölt, töltött káposzta vagy sült hús. Ilyenkor a desszert is könnyebben belefér a napba.", "Egy háromfogásos menünél nem kell mindhárom fogásnak nehéznek lennie. Tartalmas leves mellé válassz egyszerűbb főételt, vagy egy gazdag főétel elé könnyű zöldséglevest."] }
    ]
  },
  "vacsora-otletek": {
    eyebrow: "Esti ötletek",
    title: "Mit főzzek vacsorára? Egyszerű, gyors és laktató ötletek",
    intro: "Vacsorára sokszor az a legjobb választás, ami gyorsan elkészül, nem igényel sok mosogatást és a nap végén sem túl bonyolult. Összegyűjtöttünk többféle ötletet a könnyűtől a laktatóig.",
    ideas: ["Tojásos nokedli", "Sajtos-tejfölös tészta", "Lecsó", "Tócsni tejföllel", "Rántotta zöldségekkel", "Gombás rizottó", "Sült csirkecomb", "Krumplis tészta", "Túrós tészta", "Rántott sajt", "Paradicsomleves", "Palacsinta"],
    randomizerIdeas: ['Tojásos nokedli', 'Sajtos-tejfölös tészta', 'Lecsó', 'Tócsni tejföllel', 'Rántotta zöldségekkel', 'Gombás rizottó', 'Sült csirkecomb', 'Krumplis tészta', 'Túrós tészta', 'Rántott sajt', 'Paradicsomleves', 'Palacsinta', 'Bundás kenyér', 'Melegszendvics sonkával és sajttal', 'Sonkás-sajtos omlett', 'Tükörtojás sült burgonyával', 'Tojáskrémes pirítós', 'Tonhalas tésztasaláta', 'Csirkés cézársaláta', 'Görög saláta csirkével', 'Sajtos quesadilla', 'Csirkés tortilla', 'Zöldséges tortilla', 'Sült virsli hagymás krumplival', 'Kolbászos lecsó', 'Gombapaprikás', 'Tejszínes csirkés penne', 'Paradicsomos-bazsalikomos tészta', 'Pesto tészta csirkével', 'Carbonara spagetti', 'Bolognai spagetti', 'Rakott brokkoli', 'Rakott karfiol', 'Töltött melegszendvics', 'Sajtos makaróni', 'Zöldséges kuszkusz', 'Csirkés bulgur', 'Fokhagymás garnélás tészta', 'Sült camembert salátával', 'Rántott cukkini', 'Rántott gomba', 'Cukkinis tócsni', 'Kukoricás tonhalsaláta', 'Csirkés rizottó', 'Sajtos-sonkás palacsinta', 'Hortobágyi palacsinta', 'Kefires lángos', 'Túrógombóc', 'Császármorzsa', 'Grízes tészta'],
    sections: [
      { title: "Gyors vacsora 30 perc körül", paragraphs: ["A tésztaételek, tojásos fogások, egyszerű rizottók és serpenyős ételek akkor ideálisak, amikor kevés idő marad főzésre. Használj olyan alapanyagot, amelyet nem kell órákig pácolni vagy előfőzni.", "Egy gyors fogás is lehet változatos: ugyanazt az alapot más fűszerekkel, zöldségekkel vagy feltéttel teljesen más irányba viheted."], bullets: ["Tészta + sajt + tejföl gyors alap.", "Tojásból 10–15 perc alatt kész vacsora lehet.", "Maradék sült húsból szendvics vagy saláta készülhet.", "Fagyasztott zöldség gyorsítja az előkészítést."] },
      { title: "Könnyebb esti fogások", paragraphs: ["Ha későn vacsorázol, érdemes egyszerűbb adagot választani: zöldségleves, grillezett vagy natúr hús, saláta, párolt zöldség vagy kisebb adag tészta is jó lehet.", "A cél nem az, hogy minden vacsora diétás legyen, hanem hogy az étel mennyisége és összetétele illeszkedjen a napodhoz."] }
    ]
  },
  "gyors-etelek": {
    eyebrow: "Kevés időre",
    title: "Gyors ételek: ötletek, amikor 30–40 perc alatt szeretnél főzni",
    intro: "A gyors főzés kulcsa nem csak a rövid recept, hanem az egyszerű előkészítés is. Olyan fogásokat érdemes választani, amelyek kevés edényt, kevés darabolást és könnyen beszerezhető alapanyagokat igényelnek.",
    ideas: ["Tojásos nokedli", "Sajtos tészta", "Tejszínes-gombás csirke", "Lecsó", "Rántott cukkini", "Gombapaprikás", "Csirkés rizottó", "Krumplis tészta", "Tonhalas tészta", "Tócsni", "Zöldborsóleves", "Császármorzsa"],
    randomizerIdeas: ['Tojásos nokedli', 'Sajtos tészta', 'Tejszínes-gombás csirke', 'Lecsó', 'Rántott cukkini', 'Gombapaprikás', 'Csirkés rizottó', 'Krumplis tészta', 'Tonhalas tészta', 'Tócsni', 'Zöldborsóleves', 'Császármorzsa', 'Paradicsomos spagetti', 'Carbonara spagetti', 'Pestos penne', 'Sonkás-sajtos omlett', 'Rántotta baconnel', 'Bundás kenyér', 'Melegszendvics', 'Csirkés tortilla', 'Sajtos quesadilla', 'Zöldséges kuszkusz', 'Bulgur csirkemellel', 'Sült virsli krumplival', 'Paprikás krumpli', 'Zöldborsófőzelék tükörtojással', 'Finomfőzelék', 'Tejfölös gombapaprikás', 'Mustáros csirkemell', 'Mézes-mustáros csirke', 'Fokhagymás csirke serpenyőben', 'Zöldséges sült rizs', 'Tojásos sült rizs', 'Tonhalsaláta', 'Csirkés cézársaláta', 'Görög saláta', 'Rántott sajt', 'Rántott gomba', 'Sajtos makaróni', 'Túrós tészta', 'Mákos tészta', 'Diós tészta', 'Grízes tészta', 'Lángos gyors tésztából', 'Palacsinta', 'Amerikai palacsinta', 'Túrógombóc', 'Tejbegríz', 'Gyors paradicsomleves', 'Fokhagymakrémleves'],
    sections: [
      { title: "Mitől lesz valóban gyors egy étel?", paragraphs: ["A teljes időt nézd, ne csak a sütési vagy főzési perceket. Egy 20 perces fogás is elhúzódhat, ha sok hozzávalót kell pucolni és aprítani.", "A gyors recepteknél előny a serpenyő, az egyfazekas megoldás és az olyan alapanyag, amely hamar megpuhul."], bullets: ["Válassz vékonyra szeletelt húst.", "Használj gyorsan puhuló zöldségeket.", "Tarts otthon tésztát, rizst, tojást és fagyasztott zöldséget.", "Főzés közben párhuzamosítsd a köretet és a feltétet."] },
      { title: "Gyors, mégis házias", paragraphs: ["Nem kell lemondani a házias ízekről. Egy csirkepaprikás egyszerűsített változata, gombapaprikás, paprikás krumpli vagy tojásos nokedli kevésbé időigényes, mégis ismerős ízvilágot ad.", "Ha másnapra is szeretnél ebédet, válassz olyan fogást, amely újramelegítve sem veszít sokat az állagából."] }
    ]
  },
  "olcso-etelek": {
    eyebrow: "Takarékos főzés",
    title: "Olcsó ételek: pénztárcabarát ötletek hétköznapokra",
    intro: "Olcsóbban főzni nem azt jelenti, hogy minden nap ugyanaz kerül az asztalra. Burgonyából, hüvelyesekből, tésztából, rizsből, tojásból és idényzöldségekből sokféle laktató étel készíthető.",
    ideas: ["Krumplis tészta", "Paprikás krumpli", "Lencsefőzelék", "Sárgaborsó-főzelék", "Tojásos nokedli", "Káposztás tészta", "Babfőzelék", "Tócsni", "Dödölle", "Lecsó", "Zöldségleves", "Mákos tészta"],
    randomizerIdeas: ['Krumplis tészta', 'Paprikás krumpli', 'Lencsefőzelék', 'Sárgaborsó-főzelék', 'Tojásos nokedli', 'Káposztás tészta', 'Babfőzelék', 'Tócsni', 'Dödölle', 'Lecsó', 'Zöldségleves', 'Mákos tészta', 'Diós tészta', 'Grízes tészta', 'Túrós tészta', 'Sajtos tészta', 'Paradicsomos tészta', 'Krumplifőzelék', 'Tökfőzelék', 'Zöldborsófőzelék', 'Finomfőzelék', 'Kelkáposzta-főzelék', 'Lencseleves', 'Bableves', 'Krumplileves', 'Tojásleves', 'Köménymagleves', 'Paradicsomleves', 'Hamisgulyás', 'Lebbencsleves', 'Tarhonyaleves', 'Slambuc', 'Rakott krumpli', 'Rakott káposzta', 'Káposztás kocka', 'Túrós csusza', 'Bundás kenyér', 'Rántotta', 'Tükörtojás sült krumplival', 'Tojáskrémes kenyér', 'Sült virsli krumplival', 'Pásztortarhonya', 'Rizses hús egyszerűen', 'Zöldséges rizs', 'Sült rizs tojással', 'Krumplis pogácsa', 'Kenyérlángos', 'Palacsinta', 'Császármorzsa', 'Tejbegríz'],
    sections: [
      { title: "Alapanyagok, amelyekből érdemes tartani otthon", paragraphs: ["A száraz hüvelyesek, tészta, rizs, burgonya és liszt jól tárolható, sokféleképpen használható alapok. Ezekhez elég néhány friss hozzávaló, hogy teljes fogás készüljön.", "Az idényzöldségek gyakran kedvezőbb árúak, ráadásul az ízük is jobb lehet a szezonjukban."], bullets: ["Tervezd meg 3–4 napra előre a főzést.", "Használd fel a maradék köretet másnap új fogásban.", "Nagyobb adag leves vagy főzelék több étkezést lefedhet.", "A húsmentes napok csökkenthetik a heti költséget."] },
      { title: "Maradékmentés", paragraphs: ["A megmaradt rizsből zöldséges rizs, a főtt burgonyából tócsni vagy burgonyás pogácsa jellegű fogás, a sült húsból pedig szendvics vagy gyors ragu készülhet.", "A takarékos konyha egyik legfontosabb része, hogy a már elkészült ételt ne hagyd feleslegesen kárba veszni, de mindig tartsd be a biztonságos tárolás szabályait."] }
    ]
  },
  "magyaros-etelek": {
    eyebrow: "Házias ízek",
    title: "Magyaros ételek: klasszikus fogások és menüötletek",
    intro: "A magyar konyha sokféle levesből, pörköltből, főzelékből, rakott ételből, tésztából és süteményből kínál választást. Nem minden magyaros étel nehéz: a fogások jól kombinálhatók könnyebb köretekkel és szezonális zöldségekkel.",
    ideas: ["Gulyásleves", "Jókai-bableves", "Csirkepaprikás", "Töltött káposzta", "Rakott krumpli", "Túrós csusza", "Lecsó", "Brassói aprópecsenye", "Fasírt", "Halászlé", "Aranygaluska", "Somlói galuska"],
    randomizerIdeas: ['Gulyásleves', 'Jókai-bableves', 'Csirkepaprikás', 'Töltött káposzta', 'Rakott krumpli', 'Túrós csusza', 'Lecsó', 'Brassói aprópecsenye', 'Fasírt', 'Halászlé', 'Aranygaluska', 'Somlói galuska', 'Marhapörkölt', 'Sertéspörkölt', 'Birkapörkölt', 'Pacalpörkölt', 'Székelykáposzta', 'Hortobágyi húsos palacsinta', 'Paprikás krumpli', 'Bácskai rizses hús', 'Pásztortarhonya', 'Slambuc', 'Töltött paprika', 'Rakott kel', 'Rakott káposzta', 'Kelkáposzta-főzelék', 'Tökfőzelék', 'Lencsefőzelék', 'Babfőzelék', 'Sárgaborsó-főzelék', 'Tojásos nokedli', 'Káposztás tészta', 'Krumplis tészta', 'Mákos tészta', 'Diós tészta', 'Grízes tészta', 'Dödölle', 'Tócsni', 'Lángos', 'Kenyérlángos', 'Rántott hús', 'Mátrai borzaska', 'Bakonyi sertésszelet', 'Vadas marha zsemlegombóccal', 'Újházi tyúkhúsleves', 'Palócleves', 'Korhelyleves', 'Meggyleves', 'Dobostorta', 'Rákóczi túrós'],
    sections: [
      { title: "Klasszikus felépítés", paragraphs: ["Egy hagyományos magyaros ebéd lehet levesből, főételből és desszertből álló menü, de hétköznap gyakran egy tartalmas leves vagy egytálétel is elég.", "Az ízeket sokszor paprika, hagyma, fokhagyma, tejföl és friss vagy szárított fűszerek határozzák meg."], bullets: ["Tartalmas leves mellé könnyebb második fogás illik.", "Pörkölthöz galuska, tarhonya vagy burgonya gyakori köret.", "Főzelék mellé tojás vagy fasírt is jól működik.", "Desszertnek palacsinta, rétes vagy egyszerű pite is elég."] },
      { title: "Hétköznapi magyaros fogások", paragraphs: ["A rakott ételek, főzelékek, tészták és egyszerű csirkés fogások hétköznap is jól beilleszthetők. Nem szükséges minden alkalommal több órás ünnepi ételben gondolkodni.", "A klasszikus receptek jól alakíthatók a család ízléséhez: csökkenthető a zsiradék, több zöldség adható hozzá, és a köret is könnyedebbre cserélhető."] }
    ]
  },
  "hetvegi-menu": {
    eyebrow: "Ráérősebb főzés",
    title: "Hétvégi menüötletek: amikor jut idő levesre, főételre és desszertre",
    intro: "A hétvége jó alkalom arra, hogy olyan fogás készüljön, amely hétköznap túl időigényes lenne. A jó menü nem attól ünnepi, hogy minden eleme nehéz, hanem attól, hogy a fogások jól kiegészítik egymást.",
    ideas: ["Húsleves + rántott hús + almás pite", "Gulyásleves + palacsinta", "Tárkonyos raguleves + sült csirke + rétes", "Zöldségleves + töltött káposzta + madártej", "Halászlé + túrós csusza", "Jókai-bableves + aranygaluska"],
    randomizerIdeas: ['Húsleves + rántott hús + almás pite', 'Gulyásleves + palacsinta', 'Tárkonyos raguleves + sült csirke + rétes', 'Zöldségleves + töltött káposzta + madártej', 'Halászlé + túrós csusza', 'Jókai-bableves + aranygaluska', 'Újházi tyúkhúsleves + sertéssült + somlói galuska', 'Palócleves + csirkepaprikás + túrógombóc', 'Meggyleves + rántott csirkemell + gyümölcsös pite', 'Gombaleves + marhapörkölt + palacsinta', 'Karfiolleves + rakott krumpli + almás rétes', 'Zöldborsóleves + fasírt + krumplipüré + brownie', 'Húsleves + töltött paprika + madártej', 'Gulyásleves + túrós csusza + rétes', 'Babgulyás + pogácsa + palacsinta', 'Halászlé + rántott harcsa + túrós rétes', 'Tárkonyos csirkeraguleves + brassói + somlói', 'Paradicsomleves + rántott hús + almás pite', 'Krumplileves + sült csirkecomb + palacsinta', 'Májgombócleves + sertéspörkölt + aranygaluska', 'Csontleves + töltött káposzta + bejgli', 'Zöldségleves + bakonyi sertésszelet + túrógombóc', 'Gombakrémleves + sült tarja + császármorzsa', 'Brokkolikrémleves + rántott sajt + palacsinta', 'Sütőtökkrémleves + sült csirke + almás crumble', 'Fokhagymakrémleves + brassói + brownie', 'Bableves + rakott kel + máglyarakás', 'Lencseleves + fasírt + krumplipüré + pite', 'Korhelyleves + sertéssült + rétes', 'Meggyleves + csirkemell rizzsel + palacsinta', 'Almaleves + rántott sajt + túrós sütemény', 'Húsleves + vadas marha + zsemlegombóc + somlói', 'Gulyásleves + szilvás gombóc', 'Palócleves + mátrai borzaska + rétes', 'Zöldbableves + töltött paprika + madártej', 'Karalábéleves + fasírt + főzelék + piskóta', 'Csirkeraguleves + rakott karfiol + palacsinta', 'Becsinált leves + sült oldalas + almás pite', 'Halászlé + harcsapaprikás + túrós csusza', 'Babgulyás + lángos + császármorzsa', 'Húsleves + Stefánia vagdalt + krémes', 'Zöldségleves + rántott csirke + somlói', 'Paradicsomleves + rakott krumpli + rétes', 'Gombaleves + töltött káposzta + palacsinta', 'Krumplileves + pörkölt galuskával + túrógombóc', 'Tárkonyos raguleves + sült kacsa + párolt káposzta + pite', 'Újházi tyúkhúsleves + rántott sertésszelet + madártej', 'Gulyásleves + lekváros bukta', 'Meggyleves + sült csirkecomb + rizskoch', 'Jókai-bableves + túrós palacsinta'],
    sections: [
      { title: "Hogyan állíts össze három fogást?", paragraphs: ["Ha a leves gazdag és húsos, a főétel lehet kisebb vagy egyszerűbb. Ha a főétel a menü központja, előtte elég lehet egy könnyű zöldség- vagy gyümölcsleves.", "Desszertből nem szükséges nagy adag. Egy szelet pite, palacsinta vagy pohárkrém is lezárhatja az ebédet."], bullets: ["Egyensúlyozd a nehéz és könnyű fogásokat.", "Használd ugyanazokat az idényalapanyagokat több fogásban.", "A desszertet akár előző este elkészítheted.", "Olyan főételt válassz, amelyből másnapra is maradhat."] },
      { title: "Vendégváró szempontok", paragraphs: ["Vendégek esetén jó választás az előre elkészíthető leves, rakott étel vagy lassan sült hús, mert tálaláskor kevesebb feladat marad.", "Érdemes előre rákérdezni az ételallergiákra és különleges étrendi igényekre, hogy mindenki számára legyen fogyasztható fogás."] }
    ]
  },
  "egyszeru-etelek": {
    eyebrow: "Egyszerű konyha",
    title: "Egyszerű ételek kevés hozzávalóból",
    intro: "Sokszor nem különleges receptre, hanem biztos, egyszerű alapokra van szükség. Néhány hétköznapi hozzávalóból is készülhet változatos, laktató ebéd vagy vacsora.",
    ideas: ["Paprikás krumpli", "Krumplis tészta", "Tojásos nokedli", "Sajtos tészta", "Rizses hús", "Tócsni", "Lecsó", "Zöldségleves", "Túrós tészta", "Főzelék tükörtojással", "Rakott krumpli", "Palacsinta"],
    randomizerIdeas: ['Paprikás krumpli', 'Krumplis tészta', 'Tojásos nokedli', 'Sajtos tészta', 'Rizses hús', 'Tócsni', 'Lecsó', 'Zöldségleves', 'Túrós tészta', 'Főzelék tükörtojással', 'Rakott krumpli', 'Palacsinta', 'Rántotta', 'Bundás kenyér', 'Tükörtojás sült burgonyával', 'Virslis lecsó', 'Sült virsli krumplival', 'Káposztás tészta', 'Mákos tészta', 'Diós tészta', 'Grízes tészta', 'Paradicsomos tészta', 'Tejfölös tészta', 'Sonkás-sajtos tészta', 'Zöldséges rizs', 'Tojásos rizs', 'Csirkés rizs', 'Tarhonyás hús', 'Pásztortarhonya', 'Krumplifőzelék', 'Tökfőzelék', 'Zöldborsófőzelék', 'Lencsefőzelék', 'Babfőzelék', 'Sárgaborsó-főzelék', 'Finomfőzelék', 'Paradicsomleves', 'Krumplileves', 'Tojásleves', 'Köménymagleves', 'Gombaleves', 'Sajtos melegszendvics', 'Sonkás melegszendvics', 'Tojáskrémes pirítós', 'Rántott cukkini', 'Rántott gomba', 'Túrógombóc', 'Császármorzsa', 'Tejbegríz', 'Almás pite'],
    sections: [
      { title: "Kevesebb hozzávaló, kevesebb hibalehetőség", paragraphs: ["Az egyszerű ételeknél könnyebb követni a főzési időket és az ízesítést. Ha csak néhány fő alapanyagból dolgozol, az alapanyag minősége és a jó fűszerezés különösen sokat számít.", "Érdemes megtanulni néhány alapfogást, amelyet később kedved szerint tudsz bővíteni."], bullets: ["Tésztaételekhez mindig legyen otthon száraz tészta.", "Tojásból sok gyors fogás készülhet.", "Burgonya köretként és főételként is használható.", "A maradék zöldség levesbe vagy raguba kerülhet."] },
      { title: "Egyszerű heti tervezés", paragraphs: ["Válassz a hétre egy tésztás, egy burgonyás, egy rizses és egy zöldségalapú fogást. Így kevésbé lesz egyhangú az étrend, mégsem kell minden nap teljesen új alapanyagkészletet vásárolni.", "A heti terv legyen rugalmas: ami hamarabb romlik, azt főzd meg előbb, a tartósabb alapokat hagyd későbbre."] }
    ]
  },
  "maradekmento-etelek": {
    eyebrow: "Kevesebb pazarlás",
    title: "Maradékmentő ételek: ötletek a megmaradt alapanyagok felhasználásához",
    intro: "A maradékokból sokszor teljesen új fogás készíthető. A cél nem az, hogy mindent összekeverjünk, hanem hogy biztonságosan tárolt, még jó minőségű alapanyagokat tudatosan használjunk fel.",
    ideas: ["Sült rizs maradék rizsből", "Rakott étel főtt burgonyából", "Melegszendvics sült húsból", "Tésztasaláta főtt tésztából", "Zöldségkrémleves", "Tócsni burgonyából", "Fasírt maradék zöldséggel", "Palacsintatöltelék túróból", "Bundás kenyér", "Pörköltből hortobágyi palacsinta"],
    randomizerIdeas: ['Sült rizs maradék rizsből', 'Rakott étel főtt burgonyából', 'Melegszendvics sült húsból', 'Tésztasaláta főtt tésztából', 'Zöldségkrémleves', 'Tócsni burgonyából', 'Fasírt maradék zöldséggel', 'Palacsintatöltelék túróból', 'Bundás kenyér', 'Pörköltből hortobágyi palacsinta', 'Rizsfelfújt maradék rizsből', 'Rizses omlett', 'Sült rizs tojással', 'Sült rizs csirkével', 'Rizsgolyó sajttal', 'Krumplis pogácsa főtt burgonyából', 'Burgonyafasírt', 'Krumplis krokett', 'Rakott krumpli maradék sonkával', 'Burgonyakrémleves', 'Tésztás tojás maradék tésztából', 'Sajtos sült tészta', 'Sonkás tésztasaláta', 'Paradicsomos sült tészta', 'Túrós tészta maradék tésztából', 'Sült húsos tortilla', 'Sült húsos quesadilla', 'Csirkés melegszendvics', 'Húsos saláta maradék sültből', 'Sertéssültből ragu', 'Pörköltből gulyásleves', 'Pörköltből székelykáposzta', 'Maradék csirkéből rizottó', 'Maradék csirkéből tésztasaláta', 'Zöldségmaradékból omlett', 'Zöldségmaradékból frittata', 'Zöldségmaradékból rizottó', 'Zöldségmaradékból lepény', 'Zöldségmaradékból krémleves', 'Szikkadt kenyérből bundás kenyér', 'Szikkadt kenyérből kenyérpuding', 'Szikkadt kenyérből zsemlemorzsa', 'Kalácsból máglyarakás', 'Kalácsból bundás kalács', 'Túrómaradékból túrógombóc', 'Túrómaradékból körözött', 'Sajtmaradékból sajtos tészta', 'Sonkamaradékból omlett', 'Gyümölcsmaradékból turmix', 'Gyümölcsmaradékból gyümölcsleves'],
    sections: [
      { title: "Mi használható fel jól?", paragraphs: ["A főtt rizs, tészta, burgonya, sült hús és párolt zöldség sokféle új fogás alapja lehet. A maradékot mindig megfelelően hűtsd le és tárold, és csak akkor használd fel, ha biztosan megfelelő állapotú.", "A maradékmentés akkor a legegyszerűbb, ha már főzéskor tudod, melyik alapanyagból lesz több, és van ötleted a következő napi felhasználásra."], bullets: ["Címkézd a dobozokat dátummal.", "A hűtést igénylő ételt ne hagyd sokáig szobahőmérsékleten.", "Gyanús szagú vagy állagú ételt ne ments meg.", "A maradékot forrósítsd át megfelelően."] },
      { title: "Tervezett maradék", paragraphs: ["Nem minden maradék véletlen. Sokszor érdemes szándékosan több rizst, burgonyát vagy sült húst készíteni, ha másnap gyors fogást szeretnél belőle.", "Ezzel időt és energiát is spórolhatsz, miközben a heti menü változatos marad."] }
    ]
  }
} as const;
