export interface Food {
  name: string;
  source: string;
  image_src: string;
  loading?: boolean;
}

export enum FoodNumber {
  SOUP,
  MAIN,
  DESSERT,
}

type HungarianFood = Omit<Food, "loading">;

const recipeSearch = (name: string) =>
  `https://www.google.com/search?q=${encodeURIComponent(`${name} recept`)}`;

const soups: HungarianFood[] = [
  "Gulyásleves",
  "Jókai-bableves",
  "Palócleves",
  "Húsleves cérnametélttel",
  "Újházi-tyúkhúsleves",
  "Halászlé",
  "Tárkonyos csirkeraguleves",
  "Frankfurti leves",
  "Krumplileves kolbásszal",
  "Zöldborsóleves galuskával",
  "Karfiolleves",
  "Meggyleves",
  "Korhelyleves",
  "Lencseleves füstölt hússal",
  "Csipetkés babgulyás",
  "Orjaleves",
  "Csontleves",
  "Májgombócleves",
  "Grízgaluskaleves",
  "Daragaluskaleves",
  "Zöldségleves",
  "Karalábéleves",
  "Gombaleves",
  "Tejfölös gombaleves",
  "Fokhagymakrémleves",
  "Sütőtökkrémleves",
  "Brokkolikrémleves",
  "Zellerkrémleves",
  "Póréhagymakrémleves",
  "Sajtos hagymaleves",
  "Paradicsomleves betűtésztával",
  "Tojásleves",
  "Köménymagleves",
  "Savanyú tojásleves",
  "Burgonyagombóc-leves",
  "Csorbaleves",
  "Becsinált leves",
  "Bakonyi betyárleves",
  "Alföldi gulyásleves",
  "Bográcsgulyás",
  "Babgulyás csülökkel",
  "Fejtettbableves",
  "Zöldbableves",
  "Kapros zöldbableves",
  "Sárgaborsóleves",
  "Csicseriborsó-leves",
  "Lebbencsleves",
  "Slambucleves",
  "Tarhonyaleves",
  "Káposztaleves",
  "Savanyúkáposzta-leves",
  "Kel-káposztaleves",
  "Zöldséges raguleves",
  "Pulykaraguleves tárkonnyal",
  "Tejszínes csirkeraguleves",
  "Mátrai betyárleves",
  "Pandúrgulyás",
  "Palóc gulyás",
  "Hamisgulyás",
  "Minestrone magyarosan",
  "Hideg őszibarackleves",
  "Hideg eperkrémleves",
  "Almaleves fahéjjal",
  "Szilvaleves",
  "Ribizlileves",
  "Tejfölös uborkaleves",
  "Kapros tökleves",
  "Kukoricakrémleves",
  "Zöldborsókrémleves",
  "Spenótkrémleves",
].map((name) => ({ name, source: recipeSearch(name), image_src: "/soup.svg" }));

const mains: HungarianFood[] = [
  "Csirkepaprikás nokedlivel",
  "Marhapörkölt galuskával",
  "Rakott krumpli",
  "Töltött káposzta",
  "Székelykáposzta",
  "Brassói aprópecsenye",
  "Rántott hús petrezselymes krumplival",
  "Lecsó kolbásszal",
  "Túrós csusza szalonnával",
  "Rakott karfiol",
  "Hortobágyi húsos palacsinta",
  "Vadas marha zsemlegombóccal",
  "Paprikás krumpli",
  "Sólet füstölt hússal",
  "Bácskai rizses hús",
  "Stefánia vagdalt",
  "Káposztás tészta",
  "Tojásos nokedli fejes salátával",
  "Harcsapaprikás túrós csuszával",
  "Töltött paprika paradicsommártással",
  "Sertéspörkölt nokedlivel",
  "Csülökpörkölt",
  "Pacalpörkölt",
  "Körömpörkölt",
  "Kakasherepörkölt",
  "Bakonyi sertésszelet",
  "Bakonyi csirkemell",
  "Borsos tokány",
  "Hentes tokány",
  "Csikós tokány",
  "Brassói csirkemellből",
  "Mustáros sertésszelet",
  "Fokhagymás tarja",
  "Cigánypecsenye",
  "Holstein szelet",
  "Óvári sertésszelet",
  "Mátrai borzaska",
  "Dubarry csirkemell",
  "Kijevi csirkemell",
  "Rántott csirkemell",
  "Rántott sertéskaraj",
  "Rántott sajt rizzsel",
  "Rántott gomba tartármártással",
  "Rántott karfiol",
  "Párizsi szelet",
  "Natúr csirkemell párolt rizzsel",
  "Sült csirkecomb",
  "Tepsis csirke burgonyával",
  "Rozmaringos csirkecomb",
  "Mézes-mustáros csirkemell",
  "Sajttal-sonkával töltött csirkemell",
  "Göngyölt csirkemell",
  "Töltött csirke",
  "Kacsacomb párolt káposztával",
  "Libacomb hagymás tört burgonyával",
  "Sült oldalas",
  "Fokhagymás sült tarja",
  "Csülök pékné módra",
  "Sörben sült csülök",
  "Sült kolbász hagymás krumplival",
  "Hurkával sült burgonya",
  "Lecsós szelet",
  "Lecsós csirkemell",
  "Gombás sertéstokány",
  "Tejfölös-gombás csirkemell",
  "Sajtmártásos csirkemell",
  "Tejszínes-gombás csirke",
  "Rakott zöldbab",
  "Rakott kelkáposzta",
  "Rakott cukkini",
  "Rakott padlizsán",
  "Rakott brokkoli",
  "Rakott tészta",
  "Sonkás-sajtos rakott tészta",
  "Krumplis tészta",
  "Mákos tészta",
  "Diós tészta",
  "Grízes tészta baracklekvárral",
  "Túrós tészta",
  "Sajtos-tejfölös tészta",
  "Paradicsomos káposzta fasírttal",
  "Tökfőzelék fasírttal",
  "Borsófőzelék sült virslivel",
  "Zöldbabfőzelék fasírttal",
  "Lencsefőzelék sült kolbásszal",
  "Sárgaborsó-főzelék",
  "Finomfőzelék",
  "Kelkáposzta-főzelék",
  "Burgonyafőzelék",
  "Spenótfőzelék tükörtojással",
  "Sóskafőzelék főtt tojással",
  "Babfőzelék",
  "Paradicsomos húsgombóc",
  "Fasírt krumplipürével",
  "Stefánia szelet",
  "Vagdalt pogácsa",
  "Töltött dagadó",
  "Töltött csirkecomb",
  "Töltött cukkini",
  "Töltött padlizsán",
  "Töltött karalábé",
  "Töltött tök kapormártással",
  "Rakott savanyú káposzta",
  "Kolozsvári rakott káposzta",
  "Toros káposzta",
  "Lucskos káposzta",
  "Káposztás kocka",
  "Sztrapacska juhtúróval",
  "Dödölle pirított hagymával",
  "Tócsni tejföllel",
  "Lapcsánka",
  "Nokedli pörköltszafttal",
  "Lángos sajttal-tejföllel",
  "Krumplis lángos",
  "Húsos palacsinta",
  "Juhtúrós sztrapacska",
  "Krumplis nudli",
  "Grenadírmars",
  "Tarhonyás hús",
  "Rizses hús",
  "Lecsós rizs kolbásszal",
  "Gombapaprikás galuskával",
  "Zöldborsós tokány",
  "Sertésragu tarhonyával",
  "Csirkemáj baconbe tekerve",
  "Resztelt máj főtt burgonyával",
  "Hagymás rostélyos",
  "Marhaszelet vadasan",
  "Sertésszelet Budapest módra",
  "Debreceni sertésborda",
  "Cordon bleu",
  "Sajtos-tejfölös csirkemell",
  "Sertéskaraj magyarosan",
  "Harcsafilé Orly módra",
  "Rántott harcsafilé",
  "Sült hekk petrezselymes burgonyával",
  "Pontypatkó rántva",
  "Fogasfilé roston",
  "Lazac kapros mártással",
  "Tonhalas tészta",
  "Gombás rizottó",
  "Zöldséges rizottó",
  "Csirkés rizottó",
  "Milánói sertésborda",
  "Bolognai spagetti",
  "Lasagne",
  "Sajtos makaróni",
  "Csőben sült karfiol",
  "Karfiolpaprikás",
  "Zöldségfasírt",
  "Cukkinifasírt",
  "Gombafasírt",
  "Rántott cukkini",
  "Sajttal töltött gombafejek",
  "Lecsós tarhonya",
  "Krumplis lepény",
  "Hagymás bab",
  "Chilis bab magyarosan",
  "Pásztortarhonya",
  "Slambuc",
  "Öhöm",
  "Savanyú vetrece",
  "Erdélyi rakott káposzta",
].map((name) => ({ name, source: recipeSearch(name), image_src: "/main.svg" }));

const desserts: HungarianFood[] = [
  "Somlói galuska",
  "Dobostorta",
  "Eszterházy-torta",
  "Rákóczi-túrós",
  "Máglyarakás",
  "Aranygaluska vaníliasodóval",
  "Gundel-palacsinta",
  "Túrógombóc",
  "Mákos guba",
  "Madártej",
  "Kókuszkocka",
  "Zserbó",
  "Kakaós csiga",
  "Almás pite",
  "Meggyes rétes",
  "Diós bejgli",
  "Lekváros bukta",
  "Császármorzsa",
  "Túrós palacsinta",
  "Lekváros palacsinta",
  "Kakaós palacsinta",
  "Diós palacsinta",
  "Mákos palacsinta",
  "Túrós rétes",
  "Almás rétes",
  "Mákos rétes",
  "Diós rétes",
  "Meggyes pite",
  "Szilvás pite",
  "Túrós pite",
  "Rácsos linzer",
  "Lekváros linzer",
  "Isler",
  "Néró teasütemény",
  "Vaníliás kifli",
  "Hókifli",
  "Diós kifli",
  "Pozsonyi kifli",
  "Mákos bejgli",
  "Gesztenyés bejgli",
  "Gesztenyepüré tejszínhabbal",
  "Gesztenyés tekercs",
  "Piskótatekercs lekvárral",
  "Kókusztekercs",
  "Keksztekercs",
  "Sport szelet",
  "Kókuszgolyó",
  "Rumgolyó",
  "Mézes krémes",
  "Hatlapos",
  "Krémes",
  "Francia krémes",
  "Képviselőfánk",
  "Eklerfánk",
  "Szalagos fánk",
  "Csörögefánk",
  "Forgácsfánk",
  "Tarkedli",
  "Buktatorta",
  "Darázsfészek",
  "Fahéjas csiga",
  "Diós csiga",
  "Túrós batyu",
  "Lekváros derelye",
  "Szilvás gombóc",
  "Barackos gombóc",
  "Mákos nudli",
  "Diós nudli",
  "Tejbegríz fahéjjal",
  "Tejberizs",
  "Rizsfelfújt",
  "Vargabéles",
  "Stíriai metélt",
  "Túrós lepény",
  "Kapros-túrós lepény",
  "Flódni",
  "Rigó Jancsi",
  "Lúdláb torta",
  "Fekete-erdő torta",
  "Oroszkrém torta",
  "Puncstorta",
  "Sacher-torta",
  "Túró Rudi torta",
  "Túrótorta",
  "Citromtorta",
  "Diótorta",
  "Mákos torta",
  "Almatorta",
  "Gyümölcstorta",
  "Puncsszelet",
  "Dióhabos szelet",
  "Mákos guba torta",
  "Almás krémes",
  "Méteres kalács",
  "Őzgerinc",
  "Márványkuglóf",
  "Kuglóf",
  "Fonott kalács",
  "Kakaós kalács",
  "Diós kalács",
  "Lekváros kifli",
  "Hájas tészta",
  "Baracklekváros papucs",
  "Sajtos roló",
  "Habroló",
  "Vaníliás karika",
  "Pilóta keksz házilag",
  "Mézeskalács",
  "Puszedli",
  "Diós kosárka",
  "Linzerkarika",
  "Mákos linzer",
  "Almás-mákos sütemény",
  "Meggyes-mákos sütemény",
  "Bögrés meggyes",
  "Bögrés kakaós",
  "Brownie",
  "Csokis muffin",
  "Áfonyás muffin",
  "Almás muffin",
  "Panna cotta gyümölccsel",
  "Vaníliapuding",
  "Csokoládépuding",
  "Gyümölcssaláta",
  "Sült alma fahéjjal",
  "Sült körte dióval",
].map((name) => ({ name, source: recipeSearch(name), image_src: "/dessert.svg" }));

const foodByType: Record<FoodNumber, HungarianFood[]> = {
  [FoodNumber.SOUP]: soups,
  [FoodNumber.MAIN]: mains,
  [FoodNumber.DESSERT]: desserts,
};

const lastPicked: Partial<Record<FoodNumber, string>> = {};

export async function RandomFood(type: FoodNumber): Promise<Food> {
  const list = foodByType[type];
  const previous = lastPicked[type];
  const candidates = list.length > 1 ? list.filter((food) => food.name !== previous) : list;
  const picked = candidates[Math.floor(Math.random() * candidates.length)];

  lastPicked[type] = picked.name;

  return {
    ...picked,
    loading: false,
  };
}
